#pragma once

#include <driver/gpio.h>
#include <driver/spi_master.h>

#define LCD_H_RES 240
#define LCD_V_RES 320
#define LCD_BITS_PER_PIXEL 16
#define LCD_DRAW_BUFFER_LINES 30
#define LCD_DRAW_BUFFER_SIZE (LCD_H_RES * LCD_DRAW_BUFFER_LINES)
#define LCD_DOUBLE_BUFFER 1

#define LCD_PIXEL_CLOCK_HZ (20 * 1000 * 1000)
#define LCD_CMD_BITS 8
#define LCD_PARAM_BITS 8

#define LCD_SPI_HOST SPI2_HOST
#define LCD_SPI_CLK GPIO_NUM_14
#define LCD_SPI_MOSI GPIO_NUM_13
#define LCD_SPI_MISO GPIO_NUM_12
#define LCD_CS GPIO_NUM_15
#define LCD_DC GPIO_NUM_2
#define LCD_RESET GPIO_NUM_NC
#define LCD_BACKLIGHT GPIO_NUM_27
#define LCD_BACKLIGHT_LEDC_CHANNEL LEDC_CHANNEL_1
#define LCD_BACKLIGHT_LEDC_TIMER LEDC_TIMER_1

#define LCD_MIRROR_X 0
#define LCD_MIRROR_Y 0

#define TOUCH_SPI_HOST LCD_SPI_HOST
#define TOUCH_SPI_CLK LCD_SPI_CLK
#define TOUCH_SPI_MOSI LCD_SPI_MOSI
#define TOUCH_SPI_MISO LCD_SPI_MISO
#define TOUCH_CS GPIO_NUM_33
#define TOUCH_IRQ GPIO_NUM_36
#define TOUCH_RST GPIO_NUM_NC
#define TOUCH_CLOCK_HZ (2 * 1000 * 1000)
#define TOUCH_MIRROR_X 1
#define TOUCH_MIRROR_Y 1
#define TOUCH_LEFT_EDGE_X_CORRECTION_PX 16
#define TOUCH_Y_OFFSET_PX 0
